

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Energiejournaal.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class EnergyTerminalNEntities : DbContext
{
    public EnergyTerminalNEntities()
        : base("name=EnergyTerminalNEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<vwChart> vwCharts { get; set; }

    public virtual DbSet<vwData> vwDatas { get; set; }

    public virtual DbSet<vwGroup> vwGroups { get; set; }


    [DbFunction("EnergyTerminalNEntities", "fnNewsChart")]
    public virtual IQueryable<fnNewsChart_Result> fnNewsChart(Nullable<int> market_ID)
    {

        var market_IDParameter = market_ID.HasValue ?
            new ObjectParameter("Market_ID", market_ID) :
            new ObjectParameter("Market_ID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnNewsChart_Result>("[EnergyTerminalNEntities].[fnNewsChart](@Market_ID)", market_IDParameter);
    }


    [DbFunction("EnergyTerminalNEntities", "CheckValidKey")]
    public virtual IQueryable<Nullable<bool>> CheckValidKey(string key)
    {

        var keyParameter = key != null ?
            new ObjectParameter("Key", key) :
            new ObjectParameter("Key", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<bool>>("[EnergyTerminalNEntities].[CheckValidKey](@Key)", keyParameter);
    }

}

}

