
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Energiejournaal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vwChart
{

    public short ID { get; set; }

    public string Name { get; set; }

    public short Group { get; set; }

    public Nullable<byte> Period { get; set; }

    public string PeriodName { get; set; }

}

}
