//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Energiejournaal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwData
    {
        public int ID { get; set; }
        public short Chart { get; set; }
        public string ChartName { get; set; }
        public short Line { get; set; }
        public string LineName { get; set; }
        public Nullable<byte> LineType { get; set; }
        public string LineTypeName { get; set; }
        public Nullable<byte> Period { get; set; }
        public string PeriodName { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Value { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
    }
}
